"""empty message

Revision ID: 50b7377d3c10
Revises: 4e32e2d01c28
Create Date: 2019-12-26 17:05:41.812533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50b7377d3c10'
down_revision = '4e32e2d01c28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('last_content', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'last_content')
    # ### end Alembic commands ###
